// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOAbFwIco5nqVjZl_qdnI2_saIcTZ3k2M',
    appId: '1:391257333858:web:ef1d35feffd838a4d9b13b',
    messagingSenderId: '391257333858',
    projectId: 'notes-5ae78',
    authDomain: 'notes-5ae78.firebaseapp.com',
    storageBucket: 'notes-5ae78.appspot.com',
    measurementId: 'G-2D93P1TQ0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTwWvpvdQu_DlK4Dud-90AfZK89Eosg0A',
    appId: '1:391257333858:android:046e00d603b22671d9b13b',
    messagingSenderId: '391257333858',
    projectId: 'notes-5ae78',
    storageBucket: 'notes-5ae78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fyOyLDoIKF2uMzfK_TNmrdKZiLTMaOw',
    appId: '1:391257333858:ios:673bf935476d7a1dd9b13b',
    messagingSenderId: '391257333858',
    projectId: 'notes-5ae78',
    storageBucket: 'notes-5ae78.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7fyOyLDoIKF2uMzfK_TNmrdKZiLTMaOw',
    appId: '1:391257333858:ios:7db3b53d3e84adc4d9b13b',
    messagingSenderId: '391257333858',
    projectId: 'notes-5ae78',
    storageBucket: 'notes-5ae78.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
